// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmpty) Reset() {
	*x = UserEmpty{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmpty) ProtoMessage() {}

func (x *UserEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmpty.ProtoReflect.Descriptor instead.
func (*UserEmpty) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

type ConnIdMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=connId,proto3" json:"connId,omitempty"`
	ConnIp        []byte                 `protobuf:"bytes,2,opt,name=connIp,proto3" json:"connIp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnIdMsg) Reset() {
	*x = ConnIdMsg{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnIdMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnIdMsg) ProtoMessage() {}

func (x *ConnIdMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnIdMsg.ProtoReflect.Descriptor instead.
func (*ConnIdMsg) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *ConnIdMsg) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ConnIdMsg) GetConnIp() []byte {
	if x != nil {
		return x.ConnIp
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Deviceid      string                 `protobuf:"bytes,5,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	ConnId        string                 `protobuf:"bytes,6,opt,name=connId,proto3" json:"connId,omitempty"`
	ConnIp        []byte                 `protobuf:"bytes,7,opt,name=connIp,proto3" json:"connIp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *LoginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LoginRequest) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *LoginRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *LoginRequest) GetConnIp() []byte {
	if x != nil {
		return x.ConnIp
	}
	return nil
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        []byte                 `protobuf:"bytes,1,opt,name=aesKey,proto3" json:"aesKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\"\v\n" +
	"\tUserEmpty\";\n" +
	"\tConnIdMsg\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\tR\x06connId\x12\x16\n" +
	"\x06connIp\x18\x02 \x01(\fR\x06connIp\"\xbe\x01\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bdeviceid\x18\x05 \x01(\tR\bdeviceid\x12\x16\n" +
	"\x06connId\x18\x06 \x01(\tR\x06connId\x12\x16\n" +
	"\x06connIp\x18\a \x01(\fR\x06connIp\"$\n" +
	"\n" +
	"LoginReply\x12\x16\n" +
	"\x06aesKey\x18\x01 \x01(\fR\x06aesKey2p\n" +
	"\x04User\x12!\n" +
	"\aNewConn\x12\n" +
	".ConnIdMsg\x1a\n" +
	".UserEmpty\x12#\n" +
	"\x05Login\x12\r.LoginRequest\x1a\v.LoginReply\x12 \n" +
	"\x06Logout\x12\n" +
	".ConnIdMsg\x1a\n" +
	".UserEmptyB\bZ\x06./userb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_user_proto_goTypes = []any{
	(*UserEmpty)(nil),    // 0: UserEmpty
	(*ConnIdMsg)(nil),    // 1: ConnIdMsg
	(*LoginRequest)(nil), // 2: LoginRequest
	(*LoginReply)(nil),   // 3: LoginReply
}
var file_proto_user_proto_depIdxs = []int32{
	1, // 0: User.NewConn:input_type -> ConnIdMsg
	2, // 1: User.Login:input_type -> LoginRequest
	1, // 2: User.Logout:input_type -> ConnIdMsg
	0, // 3: User.NewConn:output_type -> UserEmpty
	3, // 4: User.Login:output_type -> LoginReply
	0, // 5: User.Logout:output_type -> UserEmpty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
