// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: room.proto

package server

import (
	"context"

	"github.com/Qsgs-Fans/freekill-server/service/room/internal/logic"
	"github.com/Qsgs-Fans/freekill-server/service/room/internal/svc"
	"github.com/Qsgs-Fans/freekill-server/service/room/room"
)

type RoomServer struct {
	svcCtx *svc.ServiceContext
	room.UnimplementedRoomServer
}

func NewRoomServer(svcCtx *svc.ServiceContext) *RoomServer {
	return &RoomServer{
		svcCtx: svcCtx,
	}
}

func (s *RoomServer) CreateRoom(ctx context.Context, in *room.CreateRoomRequest) (*room.CreateRoomReply, error) {
	l := logic.NewCreateRoomLogic(ctx, s.svcCtx)
	return l.CreateRoom(in)
}

// 房间应当有自动过期机制
func (s *RoomServer) JoinRoom(ctx context.Context, in *room.JoinRoomRequest) (*room.RoomEmptyReply, error) {
	l := logic.NewJoinRoomLogic(ctx, s.svcCtx)
	return l.JoinRoom(in)
}

func (s *RoomServer) LeaveRoom(ctx context.Context, in *room.LeaveRoomRequest) (*room.RoomEmptyReply, error) {
	l := logic.NewLeaveRoomLogic(ctx, s.svcCtx)
	return l.LeaveRoom(in)
}
