// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/room.proto

package room

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Room_CreateRoom_FullMethodName  = "/Room/CreateRoom"
	Room_EnterRoom_FullMethodName   = "/Room/EnterRoom"
	Room_ObserveRoom_FullMethodName = "/Room/ObserveRoom"
	Room_QuitRoom_FullMethodName    = "/Room/QuitRoom"
	Room_AddRobot_FullMethodName    = "/Room/AddRobot"
	Room_StartGame_FullMethodName   = "/Room/StartGame"
)

// RoomClient is the client API for Room service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomReply, error)
	EnterRoom(ctx context.Context, in *UidAndRidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error)
	ObserveRoom(ctx context.Context, in *UidAndRidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error)
	QuitRoom(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error)
	// TODO list
	// rpc RefreshRoomList
	AddRobot(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error)
	// rpc KickPlayer
	// rpc Ready
	StartGame(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error)
}

type roomClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomClient(cc grpc.ClientConnInterface) RoomClient {
	return &roomClient{cc}
}

func (c *roomClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomReply)
	err := c.cc.Invoke(ctx, Room_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) EnterRoom(ctx context.Context, in *UidAndRidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEmptyReply)
	err := c.cc.Invoke(ctx, Room_EnterRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) ObserveRoom(ctx context.Context, in *UidAndRidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEmptyReply)
	err := c.cc.Invoke(ctx, Room_ObserveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) QuitRoom(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEmptyReply)
	err := c.cc.Invoke(ctx, Room_QuitRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) AddRobot(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEmptyReply)
	err := c.cc.Invoke(ctx, Room_AddRobot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomClient) StartGame(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*RoomEmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomEmptyReply)
	err := c.cc.Invoke(ctx, Room_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServer is the server API for Room service.
// All implementations must embed UnimplementedRoomServer
// for forward compatibility.
type RoomServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomReply, error)
	EnterRoom(context.Context, *UidAndRidRequest) (*RoomEmptyReply, error)
	ObserveRoom(context.Context, *UidAndRidRequest) (*RoomEmptyReply, error)
	QuitRoom(context.Context, *UidRequest) (*RoomEmptyReply, error)
	// TODO list
	// rpc RefreshRoomList
	AddRobot(context.Context, *UidRequest) (*RoomEmptyReply, error)
	// rpc KickPlayer
	// rpc Ready
	StartGame(context.Context, *UidRequest) (*RoomEmptyReply, error)
	mustEmbedUnimplementedRoomServer()
}

// UnimplementedRoomServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServer struct{}

func (UnimplementedRoomServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedRoomServer) EnterRoom(context.Context, *UidAndRidRequest) (*RoomEmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterRoom not implemented")
}
func (UnimplementedRoomServer) ObserveRoom(context.Context, *UidAndRidRequest) (*RoomEmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObserveRoom not implemented")
}
func (UnimplementedRoomServer) QuitRoom(context.Context, *UidRequest) (*RoomEmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitRoom not implemented")
}
func (UnimplementedRoomServer) AddRobot(context.Context, *UidRequest) (*RoomEmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRobot not implemented")
}
func (UnimplementedRoomServer) StartGame(context.Context, *UidRequest) (*RoomEmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedRoomServer) mustEmbedUnimplementedRoomServer() {}
func (UnimplementedRoomServer) testEmbeddedByValue()              {}

// UnsafeRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServer will
// result in compilation errors.
type UnsafeRoomServer interface {
	mustEmbedUnimplementedRoomServer()
}

func RegisterRoomServer(s grpc.ServiceRegistrar, srv RoomServer) {
	// If the following call pancis, it indicates UnimplementedRoomServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Room_ServiceDesc, srv)
}

func _Room_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_EnterRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidAndRidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).EnterRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_EnterRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).EnterRoom(ctx, req.(*UidAndRidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_ObserveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidAndRidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).ObserveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_ObserveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).ObserveRoom(ctx, req.(*UidAndRidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_QuitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).QuitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_QuitRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).QuitRoom(ctx, req.(*UidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_AddRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).AddRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_AddRobot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).AddRobot(ctx, req.(*UidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Room_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Room_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServer).StartGame(ctx, req.(*UidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Room_ServiceDesc is the grpc.ServiceDesc for Room service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Room_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Room",
	HandlerType: (*RoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _Room_CreateRoom_Handler,
		},
		{
			MethodName: "EnterRoom",
			Handler:    _Room_EnterRoom_Handler,
		},
		{
			MethodName: "ObserveRoom",
			Handler:    _Room_ObserveRoom_Handler,
		},
		{
			MethodName: "QuitRoom",
			Handler:    _Room_QuitRoom_Handler,
		},
		{
			MethodName: "AddRobot",
			Handler:    _Room_AddRobot_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _Room_StartGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/room.proto",
}
